### ISSUE TITLE
add "term-of-conditions"

### ISSUE THREAD

**Issue by KumanoTanaka** [ttvnp/ttj-asset-android-client#26]
- [x] create term of use
- [x] implement at the top of tutorial.

**Comment by KumanoTanaka** [comment]
![before](https://user-images.githubusercontent.com/24493064/34547920-ed11d3a2-f141-11e7-9ce9-debe35d8a967.png)

![after](https://user-images.githubusercontent.com/24493064/34547923-f07ca850-f141-11e7-8f45-5c78456d149f.png)

**Comment by KumanoTanaka** [comment]
@m-toyoda 
> set button disable until check box is checked.
こちらも対応願えますでしょうか？

**Comment by m-toyoda** [comment]
了解です。月曜対応になります

**Comment by m-toyoda** [comment]
了解です。月曜対応になります
